#!/bin/bash

################################################################################
_info="
#===============================================================================
 FILENAME: simtee.sh
 AUTHOR:   Daniel Collins, <Daniel.Collins@enervenue.com> [DAC]

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~";
_svn=( $(printf "%s" "${_info}") 
 2022-0306-2258u 2022-0506-1817t 2022-0623-2055t 2022-0915-1120t
 2023-0124-1048u 2023-0124-1420u 2023-0203-1739u 2023-0203-1907u
 2023-0203-1913u 2023-0203-1920u 2023-0203-1930u 2023-0203-1949u
 2023-0203-2038u
); _rev=$(printf ${_svn[$((${#_svn[*]}-1))]} ) ;
unset cmdhelp; unset here ; unset _here; here=$(pwd) ; _here=$(pwd) ;

ew=MESHGEN ; OPERA="mesh";
ew=RUNSTAR ; OPERA="run";

#==============================================================================#
# FILENAME=$(basename $0);

#===============================================================================
#===============================================================================
OPT_LIC="-power";
OPERA="run" ; ## ${OPERA}
OPT_MPI="-mpi openmpi"; #"" ; # "-mpi openmpi";
OPT_GRAPH="-graphics mesa_swr";
OPT_GRAPH="";
DEF_NP=32 ;


#===============================================================================
_usage="
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 simtee.sh {OPERA} {NP} 
   -h,--h,-help,--help ) print usage and revision
 -----------------------------------------------------------------------------
 execute starccm+ in terminal-only mode (no gui):  
   \\  starccm+ -np {NP} -batch {$OPERA} [SIMFILE] | tee -a [LOGFILE]   \\
 OPERA )  operation mode: r=run, m=mesh
 NP    )  nr processors used, Mdef NP> = $DEF_NP
 --gms )  use \-graphics mesa_swr
 --nom )  NOT use \-mpi openmpi 
 [SIMFILE]: last simfile in directory automatically selected
 [LOGFILE]: autogenerated
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 ";
##===[ Functions ==========================================
fnow () { 
    now=(`date +%Y%m%d-%H%M%S`); printf $now;
};
loo () { 
    loo=$(ls -tr *log*|ta1) ;
};
pfs () { 
     OUT=$(printf "%${2}s"|sed "s/ /${1}/g"); printf '%s' $OUT;
};
pbr () { 
           printf "%s \n" $(pfs '=' 60); };
ADIV=$(pfs '-' 60);
BDIV=$(pfs '=' 60);
status(){
		pbr  
		date 
		ls -latr $PWD/ 
		pbr 
};

##=========================================================
summary(){
o="
# alias starccm  `alias starccm `
# alias starccm+ `alias starccm+`
# PATH:        ${PATH} 
"
PNOW=$(fnow);
printf "\n $BDIV \n
STAR
  STARVERS    ${STARVERS} 
  starccm     `which starccm `
  starccm+    `which starccm+`
  TIME:     	$PNOW
  RUNDIR:   	$RUNDIR
  SIMFILE:		$SIMFILE
  SIMCASE:  	$SIMCASE
  LOGFILE:  	$loo

 OPTIONS:     $OPTIONS
  * lic:      $OPT_LIC :( license ): 
  * NP:        $NP  \\ :(number of processor cores ):\\
  * OPERA:     $OPERA \\ :(run, mesh, gui, java :\\
  * OPT_MPI:   $OPT_MPI  \\ \t\t:(-mpi openmpi) \\
  * OPT_GRAPH: $OPT_GRAPH \\ \t\t:(-graphics ): \\
* ----------------------------------------------------------
>> Executing: $doing \n $BDIV \n" ;
	}

pp(){ printf "$1%.s" $(seq 1 $2) ; } 
showrev(){ 
      printf "\n%s< REV: %s >\n" $(pp '_' 56) ${_rev} ;
 #    printf "\n $_usage \n"
}
#####++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#####
bootup(){
  #HUB='/home/common/sh' ;
  #CLIB='/home/common/clib' ;
  #   sh_runsim="${HUB}/runsim.sh" ;
  #alias runsim=" . ${HUB}/runsim.sh" ;
#===============================================================================
## initialise settings quietly from setstar.sh:
   ${HUB}/setstar.sh q ; 
#  alias starccm=/opt/Siemens/${STARVERS}/STAR-CCM+${STARVERS}/star/bin/starccm+ ;
   which starccm+ ;

#===============================================================================
  qstar='/home/common/lib/qstar.py' ;
  qstar='/home/common/clib/qstar.py';
  alias qstar=" $qstar $1 " ;
}

###-----------------------------------------------------------------------------
middle(){
  if [[ "${OPERA}" == "mesh" ]] ; then 
    memorywatch.sh i 4 s 15 &
  fi
#   /opt/Siemens/${STARVERS}/STAR-CCM+${STARVERS}/star/bin/starccm+ \
#      ${OPT_LIC} ${OPT_MPI} -np ${NP} -batch ${OPERA} ${SIMFILE} | tee -a ${loo} 
   exec ${doing}  | tee -a $loo ;

}

###-----------------------------------------------------------------------------

end(){
  touch ./STOP ;
  touch ./END_$ew ;

  status  | tee -a $loo ;
  tail -n 20 $loo ;

  if [[ "${OPERA}" == "mesh" ]] ; then 
    #if [[ -f ./memorysum.txt ]] ; then 
    /home/common/sh/gen_memusage.sh &
  fi
  if [[ "${OPERA}" == "run" ]] ; then 
	  mkdir -pv  rep/loo/ ;
	  /home/common/lib/qstar.py ; ### exec:python3 qstar ;
    cp -vfp --preserve=timestamps $loo.stat.txt  ${SIMCASE}.runstat.txt_$(fnow) ;
    cp -vfp --preserve=timestamps *runstat* *run.log* rep/loo/ ;
    mv -v *.png rep/ ;

  fi;
  status  | tee -a $loo ;
  PNOW=$(fnow) ;
  cp -pvf $loo ${SIMCASE}.${OPERA}.log_$(fnow) ;

  . /home/common/sh/calc_stardur.sh ${OPERA} ;

} 
###-----------------------------------------------------------------------------


exes() { #~~~
  ( bootup ) ;
  printf " STARVERS : ${STARVERS} \n" ;
  touch ./BEG_$ew ;

  RUNDIR=$( pwd );
  SIMFILE=$(ls -tr *.sim | grep -v sim~ | tail -n1 ) ;
  SIMCASE=$(basename -a ${SIMFILE%%.sim} ) ;
  loo=${RUNDIR}/${SIMCASE}_${OPERA}.log ;

  printf " RUNDIR : ${RUNDIR}  \n" ;
  printf " SIMFILE: ${SIMFILE} \n" ;
  printf " SIMCASE: ${SIMCASE} \n" ;
  printf " loo    : ${loo}     \n" ;

  if [ $(ls -tr ${loo} | tail -n1) ]; then
       cp -vf --preserve=timestamps ${loo} ${loo}__$( 
		   printf $(ls -la --time-style='+%Y%m%d-%H%M' ${loo} |awk '{print $6}')) ;
  fi;

  OPTIONS="$OPT_LIC $OPT_NP $OPT_MPI $OPT_GRAPH $OPERA ";

# doing="/opt/Siemens/${STARVERS}/STAR-CCM+${STARVERS}/star/bin/starccm+ -power ${OPT_MPI} -np ${NP} -batch ${OPERA} ${SIMFILE} | tee -a ${loo} " ;

  doing="starccm+ -power ${OPT_MPI} -np ${NP} -batch ${OPERA} ${SIMFILE} | tee -a ${loo} " ;
  doing="starccm+ -power ${OPT_MPI} -np ${NP} -batch ${OPERA} ${SIMFILE} " ;

  summary  | tee -a $loo
# status   | tee -a $loo

  ( middle ) ;
  ( end )    ;

}


#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#      
#  Getting Option values from Input Arguments
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#      
  while [[ ${#@} -gt 0 ]] ; do key="${1}" ; 
	  case "$key" in 
 	   -h|--h|-help|--help) cmdhelp="h"; break 
     ;;
	   m|mesh|-m|-mesh  ) ## mesh
          shift; 
          OPERA="mesh"; ew="MESHGEN" ;
          #shift; 
          NP=${1};
#         shift; 
#         OPT_GRAPHICS="";
          echo " $OPERA $ew "
     ;;
	   r|run|-r|-run    ) ## run
          shift; 
          OPERA="run";  ew="RUNSTAR" ;
          #shift; 
          NP=${1};
#         shift; 
#         OPT_GRAPHICS="";
          echo " $OPERA $ew "
     ;;
#    --gms  ) ## option ON  graphics mes_swr 
#         shift; 
#         OPT_GRAPH="";                       ## default opt graphics
#         OPT_GRAPHICS="-graphics mesa_swr"   ## toggle on   graphics mesa_swr
#    ;;
#    -n-om  ) ## option OFF mpi openmpi 
#         shift; 
#         OPT_MPI="-mpi openmpi"              ## def opt for mpi
#         OPT_MPI=""                          ## toggle off  openmpi
#    ;;
#     *) NP=${1} 
#     ;; 
    esac 
   shift 
  done ;
##=========================================================
  if [[ "${cmdhelp}" == "h" ]] ; then
     printf "${_usage}" ; (showrev) ;
  else 
    if [ -z ${NP} ] ; then	 NP=$DEF_NP; fi
    if [ $(echo "$NP - 1 >0" | bc -l) -eq 1 ] ; then OPT_NP="-np ${NP}"; else OPT_NP=""; fi
    printf "
 ¨¨¨¨¨ Executing this Operation [ %s ] \n at: \n\t $(date +%s) $(date +%Y%m%d-%H%M) \n
 ¨¨¨¨¨ \n" \
       "${OPERA}" ;
    ( exes ) ;
  fi
##============================================================================##
printf " END OF EXECUTION : $(date +%s) $(date +%Y%m%d-%H%M) \n" ;
printf " \f \n";
unset cmdhelp; unset here ; unset _here; here=$(pwd) ; _here=$(pwd) ;
##============================================================================##

################################################################################
#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~
#                             #[[ END OF SCRIPT ]]#                            #
#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~#~~~~
################################################################################
